version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_backend
    command: >
      sh -lc "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn djangoProject.wsgi:application
        --bind 0.0.0.0:8200
        --workers 3
        --timeout 60
      "
    ports:
      - "8200:8200"
    env_file:
      - .env
    environment:
      DJANGO_BASE_URL: http://backend:8200
    volumes:
      - ./creds:/app/creds:ro
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: prml_event_bot
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DJANGO_BASE_URL: http://backend:8200
      API_BASE_URL: http://backend:8200
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - media_volume:/app/media
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: prml_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 20

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_celery_worker
    command: celery -A djangoProject worker -l info --concurrency=4
    env_file:
      - .env
    volumes:
      - ./creds:/app/creds:ro
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_celery_beat
    command: celery -A djangoProject beat -l info
    env_file:
      - .env
    volumes:
      - ./creds:/app/creds:ro
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  media_volume:
  static_volume:
