services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_backend
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn djangoProject.wsgi:application --bind 0.0.0.0:8200 --workers 3
      "
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - ./creds:/app/creds:ro
    ports:
      - "8200:8200"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: prml_event_bot
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_BASE_URL: http://backend:8200
    volumes:
      - media_volume:/app/media
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: prml_redis
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_celery_worker
    command: celery -A djangoProject worker -l info --concurrency=4
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - ./creds:/app/creds:ro
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_celery_beat
    # якщо ти реально використовуєш django-celery-beat — ок.
    # якщо НЕ використовуєш, скажи — я спрощу на звичайний beat
    command: celery -A djangoProject beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - ./creds:/app/creds:ro
      - celerybeat_data:/app/celerybeat
    env_file:
      - .env
    environment:
      # щоб celerybeat schedule НЕ створював файли в корені
      CELERYBEAT_SCHEDULE_FILENAME: /app/celerybeat/celerybeat-schedule
    depends_on:
      - redis
      - backend
    restart: unless-stopped

volumes:
  media_volume:
  static_volume:
  celerybeat_data:
