services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_backend
    command: python manage.py runserver 0.0.0.0:8200
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    expose:
      - "8200"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: prml_nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      # якщо SSL буде в nginx контейнері:
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/var/www/prml_event_bot/media:ro
      - static_volume:/var/www/prml_event_bot/static:ro
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: prml_event_bot
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_BASE_URL: http://backend:8200
    volumes:
      - media_volume:/app/media
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: prml_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_celery_worker
    command: celery -A djangoProject worker -l info
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prml_celery_beat
    command: celery -A djangoProject beat -l info
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    restart: unless-stopped

volumes:
  media_volume:
  static_volume:
